In [2]:
import pandas as pd

In [6]:
df = pd.read_csv('flights.csv')
df

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00
5,6,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01 05:00:00
6,7,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,2013-01-01 06:00:00
7,8,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,2013-01-01 06:00:00
8,9,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,2013-01-01 06:00:00
9,10,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,2013-01-01 06:00:00
10,11,2013,1,1,558.0,600,-2.0,849.0,851,-2.0,B6,49,N793JB,JFK,PBI,149.0,1028,6,0,2013-01-01 06:00:00
11,12,2013,1,1,558.0,600,-2.0,853.0,856,-3.0,B6,71,N657JB,JFK,TPA,158.0,1005,6,0,2013-01-01 06:00:00
12,13,2013,1,1,558.0,600,-2.0,924.0,917,7.0,UA,194,N29129,JFK,LAX,345.0,2475,6,0,2013-01-01 06:00:00
13,14,2013,1,1,558.0,600,-2.0,923.0,937,-14.0,UA,1124,N53441,EWR,SFO,361.0,2565,6,0,2013-01-01 06:00:00
14,15,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,707,N3DUAA,LGA,DFW,257.0,1389,6,0,2013-01-01 06:00:00
15,16,2013,1,1,559.0,559,0.0,702.0,706,-4.0,B6,1806,N708JB,JFK,BOS,44.0,187,5,59,2013-01-01 05:00:00
16,17,2013,1,1,559.0,600,-1.0,854.0,902,-8.0,UA,1187,N76515,EWR,LAS,337.0,2227,6,0,2013-01-01 06:00:00
17,18,2013,1,1,600.0,600,0.0,851.0,858,-7.0,B6,371,N595JB,LGA,FLL,152.0,1076,6,0,2013-01-01 06:00:00
18,19,2013,1,1,600.0,600,0.0,837.0,825,12.0,MQ,4650,N542MQ,LGA,ATL,134.0,762,6,0,2013-01-01 06:00:00
19,20,2013,1,1,601.0,600,1.0,844.0,850,-6.0,B6,343,N644JB,EWR,PBI,147.0,1023,6,0,2013-01-01 06:00:00
20,21,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,1919,N971DL,LGA,MSP,170.0,1020,6,10,2013-01-01 06:00:00
21,22,2013,1,1,602.0,605,-3.0,821.0,805,16.0,MQ,4401,N730MQ,LGA,DTW,105.0,502,6,5,2013-01-01 06:00:00
22,23,2013,1,1,606.0,610,-4.0,858.0,910,-12.0,AA,1895,N633AA,EWR,MIA,152.0,1085,6,10,2013-01-01 06:00:00
23,24,2013,1,1,606.0,610,-4.0,837.0,845,-8.0,DL,1743,N3739P,JFK,ATL,128.0,760,6,10,2013-01-01 06:00:00
24,25,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,1077,N53442,EWR,MIA,157.0,1085,6,7,2013-01-01 06:00:00
25,26,2013,1,1,608.0,600,8.0,807.0,735,32.0,MQ,3768,N9EAMQ,EWR,ORD,139.0,719,6,0,2013-01-01 06:00:00
26,27,2013,1,1,611.0,600,11.0,945.0,931,14.0,UA,303,N532UA,JFK,SFO,366.0,2586,6,0,2013-01-01 06:00:00
27,28,2013,1,1,613.0,610,3.0,925.0,921,4.0,B6,135,N635JB,JFK,RSW,175.0,1074,6,10,2013-01-01 06:00:00
28,29,2013,1,1,615.0,615,0.0,1039.0,1100,-21.0,B6,709,N794JB,JFK,SJU,182.0,1598,6,15,2013-01-01 06:00:00
29,30,2013,1,1,615.0,615,0.0,833.0,842,-9.0,DL,575,N326NB,EWR,ATL,120.0,746,6,15,2013-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336746,336747,2013,9,30,2123.0,2125,-2.0,2223.0,2247,-24.0,EV,5489,N712EV,LGA,CHO,45.0,305,21,25,2013-09-30 21:00:00
336747,336748,2013,9,30,2127.0,2129,-2.0,2314.0,2323,-9.0,EV,3833,N16546,EWR,CLT,72.0,529,21,29,2013-09-30 21:00:00
336748,336749,2013,9,30,2128.0,2130,-2.0,2328.0,2359,-31.0,B6,97,N807JB,JFK,DEN,213.0,1626,21,30,2013-09-30 21:00:00
336749,336750,2013,9,30,2129.0,2059,30.0,2230.0,2232,-2.0,EV,5048,N751EV,LGA,RIC,45.0,292,20,59,2013-09-30 20:00:00
336750,336751,2013,9,30,2131.0,2140,-9.0,2225.0,2255,-30.0,MQ,3621,N807MQ,JFK,DCA,36.0,213,21,40,2013-09-30 21:00:00
336751,336752,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,2013-09-30 21:00:00
336752,336753,2013,9,30,2142.0,2129,13.0,2250.0,2239,11.0,EV,4509,N12957,EWR,PWM,47.0,284,21,29,2013-09-30 21:00:00
336753,336754,2013,9,30,2145.0,2145,0.0,115.0,140,-25.0,B6,1103,N633JB,JFK,SJU,192.0,1598,21,45,2013-09-30 21:00:00
336754,336755,2013,9,30,2147.0,2137,10.0,30.0,27,3.0,B6,1371,N627JB,LGA,FLL,139.0,1076,21,37,2013-09-30 21:00:00
336755,336756,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,523,N813UA,EWR,BOS,37.0,200,21,56,2013-09-30 21:00:00
336756,336757,2013,9,30,2150.0,2159,-9.0,2250.0,2306,-16.0,EV,3842,N10575,EWR,MHT,39.0,209,21,59,2013-09-30 21:00:00
336757,336758,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30 18:00:00
336758,336759,2013,9,30,2203.0,2205,-2.0,2339.0,2331,8.0,EV,5311,N722EV,LGA,BGR,61.0,378,22,5,2013-09-30 22:00:00
336759,336760,2013,9,30,2207.0,2140,27.0,2257.0,2250,7.0,MQ,3660,N532MQ,LGA,BNA,97.0,764,21,40,2013-09-30 21:00:00
336760,336761,2013,9,30,2211.0,2059,72.0,2339.0,2242,57.0,EV,4672,N12145,EWR,STL,120.0,872,20,59,2013-09-30 20:00:00
336761,336762,2013,9,30,2231.0,2245,-14.0,2335.0,2356,-21.0,B6,108,N193JB,JFK,PWM,48.0,273,22,45,2013-09-30 22:00:00
336762,336763,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-09-30 21:00:00
336763,336764,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-09-30 20:00:00
336764,336765,2013,9,30,2237.0,2245,-8.0,2345.0,2353,-8.0,B6,234,N318JB,JFK,BTV,43.0,266,22,45,2013-09-30 22:00:00
336765,336766,2013,9,30,2240.0,2245,-5.0,2334.0,2351,-17.0,B6,1816,N354JB,JFK,SYR,41.0,209,22,45,2013-09-30 22:00:00
336766,336767,2013,9,30,2240.0,2250,-10.0,2347.0,7,-20.0,B6,2002,N281JB,JFK,BUF,52.0,301,22,50,2013-09-30 22:00:00
336767,336768,2013,9,30,2241.0,2246,-5.0,2345.0,1,-16.0,B6,486,N346JB,JFK,ROC,47.0,264,22,46,2013-09-30 22:00:00
336768,336769,2013,9,30,2307.0,2255,12.0,2359.0,2358,1.0,B6,718,N565JB,JFK,BOS,33.0,187,22,55,2013-09-30 22:00:00
336769,336770,2013,9,30,2349.0,2359,-10.0,325.0,350,-25.0,B6,745,N516JB,JFK,PSE,196.0,1617,23,59,2013-09-30 23:00:00
336770,336771,2013,9,30,NaN,1842,NaN,NaN,2019,NaN,EV,5274,N740EV,LGA,BNA,NaN,764,18,42,2013-09-30 18:00:00
336771,336772,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00
336772,336773,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00
336773,336774,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00
336774,336775,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00
336775,336776,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00

Berapa banyak penerbangan di bulan Januari?

In [114]:
len(df[df['month'] == 1])

27004

Berapa banyak penerbangan di bulan Januari hingga April?

In [55]:
len(df[df['month'] < 5])

109119

Berapa banyak penerbangan di bulan Januari yang berasal dari bandara JFK?

In [128]:
len(df[(df['month'] == 1) & (df['origin'] == 'JFK')])

9161

Berikan _tail number_, tujuan dan _delay_ kedatangan untuk penerbangan bulan Januari dari JFK yang tidak mengalami _delay_ keberangkatan.

In [68]:
df[(df['month'] == 1) & (df['origin'] == 'JFK') & (df['dep_delay'] <= 0)][['tailnum', 'dest', 'arr_delay']]

      tailnum dest  arr_delay
3      N804JB  BQN      -18.0
8      N593JB  MCO       -8.0
10     N793JB  PBI       -2.0
11     N657JB  TPA       -3.0
12     N29129  LAX        7.0
15     N708JB  BOS       -4.0
23     N3739P  ATL       -8.0
28     N794JB  SJU      -21.0
35     N535UW  PHX        0.0
36     N3BAAA  SJU       -3.0
44     N805JB  BOS      -10.0
48     N796JB  BUF        5.0
51     N558JB  LAS       -6.0
52     N178JB  MSY       11.0
54     N3763D  SLC       -9.0
55     N705TW  SFO       -8.0
58     N5FMAA  MCO      -10.0
63     N627VA  LAX        2.0
65     N646JB  FLL        1.0
71     N651JB  SJU      -15.0
72     N3ETAA  FLL      -12.0
75     N562JB  MCO        5.0
82     N635VA  SFO      -26.0
83     N304JB  ROC       -1.0
86     N552JB  SYR        4.0
87     N625JB  SFO      -26.0
92     N624JB  SRQ      -11.0
94     N336AA  SFO       10.0
104    N955DL  MIA      -30.0
106    N828MQ  RDU       -6.0
...       ...  ...        ...
26674  N922MQ  BNA       26.0
26677  N504JB  BTV      -20.0
26688   N3753  PDX       -1.0
26689  N339AA  SFO       21.0
26691  N525UA  LAX       16.0
26693  N612JB  MCO       39.0
26698  N547JB  LGB       10.0
26699  N534JB  SJC       22.0
26716  N516JB  LAS       23.0
26720  N3FKAA  SEA       -9.0
26727  N906MQ  BWI       44.0
26732  N3769L  SEA        2.0
26743  N3741S  MCO        9.0
26746  N175DZ  ATL        7.0
26748  N722TW  SFO       -2.0
26755  N805JB  SLC       -2.0
26762  N3762Y  LAS      -12.0
26763  N3754A  PHX       17.0
26765  N393DA  FLL       19.0
26767  N3763D  SLC      -15.0
26768  N8924B  CLT        6.0
26776  N649JB  OAK       -1.0
26785  N3JPAA  TPA       33.0
26820  N505UA  LAX       35.0
26832  N529JB  PDX      -11.0
26836  N334JB  MSY       22.0
26854  N710TW  LAX      -18.0
26881  N319AA  LAX       19.0
26908  N708JB  BOS      -19.0
26910  N794JB  BUF       -2.0

[5967 rows x 3 columns]

Berikan _tail number_ dari semua penerbangan US Airways (kode maskapai: US). Ada berapa _tail number_ unik dari penerbangan-penerbangan US Airways?

In [130]:
dfusairways = df[df['carrier'] == 'US']
print(dfusairways['tailnum'].dropna().unique(), "\n", len(dfusairways['tailnum'].dropna().unique()))

['N807AW' 'N535UW' 'N426US' 'N178US' 'N543UW' 'N654AW' 'N655AW' 'N959UW'
 'N642AW' 'N765US' 'N541UW' 'N162UW' 'N712US' 'N951UW' 'N169UW' 'N755US'
 'N540UW' 'N957UW' 'N177US' 'N560UW' 'N539UW' 'N738US' 'N550UW' 'N649AW'
 'N188US' 'N680AW' 'N510UW' 'N460UW' 'N745VJ' 'N445US' 'N837AW' 'N545UW'
 'N538UW' 'N565UW' 'N945UW' 'N537UW' 'N656AW' 'N747UW' 'N651AW' 'N667AW'
 'N702UW' 'N547UW' 'N764US' 'N185UW' 'N180US' 'N751UW' 'N648AW' 'N668AW'
 'N449US' 'N552UW' 'N172US' 'N767UW' 'N438US' 'N520UW' 'N171US' 'N801AW'
 'N952UW' 'N196UW' 'N601AW' 'N676AW' 'N760US' 'N561UW' 'N710UW' 'N163US'
 'N197UW' 'N664AW' 'N406US' 'N186US' 'N420US' 'N825AW' 'N170US' 'N508AY'
 'N192UW' 'N677AW' 'N758US' 'N756US' 'N948UW' 'N179UW' 'N555AY' 'N723UW'
 'N658AW' 'N544UW' 'N430US' 'N721UW' 'N821AW' 'N554UW' 'N673AW' 'N675AW'
 'N548UW' 'N763US' 'N730US' 'N167US' 'N737US' 'N176UW' 'N174US' 'N173US'
 'N433US' 'N749US' 'N103US' 'N769US' 'N519UW' 'N650AW' 'N804AW' 'N193UW'
 'N546UW' 'N117UW' 'N947UW' 'N564UW' 'N716UW' 'N187US' 'N509AY' 'N409US'
 'N566UW' 'N754UW' 'N524UW' 'N752US' 'N184US' 'N722US' 'N958UW' 'N770UW'
 'N669AW' 'N753US' 'N944UW' 'N659AW' 'N713UW' 'N657AW' 'N557UW' 'N602AW'
 'N762US' 'N663AW' 'N701UW' 'N724UW' 'N965UW' 'N768US' 'N812AW' 'N563UW'
 'N653AW' 'N604AW' 'N123UW' 'N624AW' 'N652AW' 'N183UW' 'N181UW' 'N711UW'
 'N744P' 'N553UW' 'N740UW' 'N110UW' 'N949UW' 'N647AW' 'N665AW' 'N725UW'
 'N559UW' 'N961UW' 'N189UW' 'N523UW' 'N954UW' 'N704US' 'N194UW' 'N660AW'
 'N672AW' 'N558UW' 'N551UW' 'N950UW' 'N678AW' 'N714US' 'N443US' 'N556UW'
 'N107US' 'N195UW' 'N452UW' 'N113UW' 'N953UW' 'N542UW' 'N104UW' 'N946UW'
 'N956UW' 'N679AW' 'N715UW' 'N661AW' 'N766US' 'N703UW' 'N662AW' 'N757UW'
 'N108UW' 'N746UW' 'N748UW' 'N741UW' 'N709UW' 'N182UW' 'N536UW' 'N742PS'
 'N521UW' 'N708UW' 'N831AW' 'N112US' 'N444US' 'N118US' 'N125UW' 'N432US'
 'N562UW' 'N549UW' 'N124US' 'N733UW' 'N717UW' 'N700UW' 'N955UW' 'N161UW'
 'N126UW' 'N838AW' 'N127UW' 'N111US' 'N109UW' 'N114UW' 'N705UW' 'N732US'
 'N102UW' 'N156UW' 'N157UW' 'N154UW' 'N568UW' 'N198UW' 'N128UW' 'N507AY'
 'N199UW' 'N567UW' 'N165US' 'N640AW' 'N191UW' 'N121UW' 'N963UW' 'N151UW'
 'N190UW' 'N150UW' 'N628AW' 'N153UW' 'N152UW' 'N750UW' 'N569UW' 'N534UW'
 'N122US' 'N155UW' 'N119US' 'N967UW' 'N435US' 'N810AW' 'N105UW' 'N440US'
 'N941UW' 'N434US' 'N633AW' 'N571UW' 'N570UW' 'N439US' 'N450UW' 'N245AY'
 'N802AW' 'N427US' 'N824AW' 'N572UW' 'N834AW' 'N457UW' 'N455UW' 'N627AW'
 'N459UW' 'N419US' 'N830AW' 'N814AW' 'N626AW' 'N453UW' 'N632AW' 'N456UW'
 'N441US' 'N631AW' 'N442US' 'N836AW' 'N451UW' 'N827AW' 'N625AW' 'N828AW'
 'N622AW' 'N820AW' 'N809AW' 'N826AW' 'N817AW' 'N819AW' 'N815AW' 'N835AW'
 'N940UW']
 289

In [131]:
print(df[df['carrier'] == 'US']['tailnum'].dropna().unique(), "\n", len(df[df['carrier'] == 'US']['tailnum'].dropna().unique()))

['N807AW' 'N535UW' 'N426US' 'N178US' 'N543UW' 'N654AW' 'N655AW' 'N959UW'
 'N642AW' 'N765US' 'N541UW' 'N162UW' 'N712US' 'N951UW' 'N169UW' 'N755US'
 'N540UW' 'N957UW' 'N177US' 'N560UW' 'N539UW' 'N738US' 'N550UW' 'N649AW'
 'N188US' 'N680AW' 'N510UW' 'N460UW' 'N745VJ' 'N445US' 'N837AW' 'N545UW'
 'N538UW' 'N565UW' 'N945UW' 'N537UW' 'N656AW' 'N747UW' 'N651AW' 'N667AW'
 'N702UW' 'N547UW' 'N764US' 'N185UW' 'N180US' 'N751UW' 'N648AW' 'N668AW'
 'N449US' 'N552UW' 'N172US' 'N767UW' 'N438US' 'N520UW' 'N171US' 'N801AW'
 'N952UW' 'N196UW' 'N601AW' 'N676AW' 'N760US' 'N561UW' 'N710UW' 'N163US'
 'N197UW' 'N664AW' 'N406US' 'N186US' 'N420US' 'N825AW' 'N170US' 'N508AY'
 'N192UW' 'N677AW' 'N758US' 'N756US' 'N948UW' 'N179UW' 'N555AY' 'N723UW'
 'N658AW' 'N544UW' 'N430US' 'N721UW' 'N821AW' 'N554UW' 'N673AW' 'N675AW'
 'N548UW' 'N763US' 'N730US' 'N167US' 'N737US' 'N176UW' 'N174US' 'N173US'
 'N433US' 'N749US' 'N103US' 'N769US' 'N519UW' 'N650AW' 'N804AW' 'N193UW'
 'N546UW' 'N117UW' 'N947UW' 'N564UW' 'N716UW' 'N187US' 'N509AY' 'N409US'
 'N566UW' 'N754UW' 'N524UW' 'N752US' 'N184US' 'N722US' 'N958UW' 'N770UW'
 'N669AW' 'N753US' 'N944UW' 'N659AW' 'N713UW' 'N657AW' 'N557UW' 'N602AW'
 'N762US' 'N663AW' 'N701UW' 'N724UW' 'N965UW' 'N768US' 'N812AW' 'N563UW'
 'N653AW' 'N604AW' 'N123UW' 'N624AW' 'N652AW' 'N183UW' 'N181UW' 'N711UW'
 'N744P' 'N553UW' 'N740UW' 'N110UW' 'N949UW' 'N647AW' 'N665AW' 'N725UW'
 'N559UW' 'N961UW' 'N189UW' 'N523UW' 'N954UW' 'N704US' 'N194UW' 'N660AW'
 'N672AW' 'N558UW' 'N551UW' 'N950UW' 'N678AW' 'N714US' 'N443US' 'N556UW'
 'N107US' 'N195UW' 'N452UW' 'N113UW' 'N953UW' 'N542UW' 'N104UW' 'N946UW'
 'N956UW' 'N679AW' 'N715UW' 'N661AW' 'N766US' 'N703UW' 'N662AW' 'N757UW'
 'N108UW' 'N746UW' 'N748UW' 'N741UW' 'N709UW' 'N182UW' 'N536UW' 'N742PS'
 'N521UW' 'N708UW' 'N831AW' 'N112US' 'N444US' 'N118US' 'N125UW' 'N432US'
 'N562UW' 'N549UW' 'N124US' 'N733UW' 'N717UW' 'N700UW' 'N955UW' 'N161UW'
 'N126UW' 'N838AW' 'N127UW' 'N111US' 'N109UW' 'N114UW' 'N705UW' 'N732US'
 'N102UW' 'N156UW' 'N157UW' 'N154UW' 'N568UW' 'N198UW' 'N128UW' 'N507AY'
 'N199UW' 'N567UW' 'N165US' 'N640AW' 'N191UW' 'N121UW' 'N963UW' 'N151UW'
 'N190UW' 'N150UW' 'N628AW' 'N153UW' 'N152UW' 'N750UW' 'N569UW' 'N534UW'
 'N122US' 'N155UW' 'N119US' 'N967UW' 'N435US' 'N810AW' 'N105UW' 'N440US'
 'N941UW' 'N434US' 'N633AW' 'N571UW' 'N570UW' 'N439US' 'N450UW' 'N245AY'
 'N802AW' 'N427US' 'N824AW' 'N572UW' 'N834AW' 'N457UW' 'N455UW' 'N627AW'
 'N459UW' 'N419US' 'N830AW' 'N814AW' 'N626AW' 'N453UW' 'N632AW' 'N456UW'
 'N441US' 'N631AW' 'N442US' 'N836AW' 'N451UW' 'N827AW' 'N625AW' 'N828AW'
 'N622AW' 'N820AW' 'N809AW' 'N826AW' 'N817AW' 'N819AW' 'N815AW' 'N835AW'
 'N940UW']
 289

Tampilkan penerbangan dengan _delay_ keberangkatan terlama di bulan Januari.

In [48]:
dfjan = df[df['month'] == 1]
dfsortedjanuary = dfjan.sort_values(by = 'dep_delay')
dfsortedjanuary.dropna().tail(1)

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
7072,7073,2013,1,9,641.0,900,1301.0,1242.0,1530,1272.0,HA,51,N384HA,JFK,HNL,640.0,4983,9,0,2013-01-09 09:00:00

In [132]:
d = df[df['month'] == 1]
dep = d['dep_delay'].agg('max') # nilai ini dipakai untuk memilih penerbangan dengan dep_delay terlama
df[df['dep_delay'] == dep]

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
7072,7073,2013,1,9,641.0,900,1301.0,1242.0,1530,1272.0,HA,51,N384HA,JFK,HNL,640.0,4983,9,0,2013-01-09 09:00:00

In [133]:
d = df[df['month'] == 1]
d[d['dep_delay'] == d['dep_delay'].max()]

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
7072,7073,2013,1,9,641.0,900,1301.0,1242.0,1530,1272.0,HA,51,N384HA,JFK,HNL,640.0,4983,9,0,2013-01-09 09:00:00

Tunjukkan asal dan tujuan penerbangan selain milik maskapai US, UA, DL, dan B6.

In [134]:
df[(df['carrier'] != 'US') & (df['carrier'] != 'UA') & (df['carrier'] != 'DL') & (df['carrier'] != 'B6')][['origin', 'dest']]

       origin dest
2         JFK  MIA
7         LGA  IAD
9         LGA  ORD
14        LGA  DFW
18        LGA  ATL
21        LGA  DTW
22        EWR  MIA
25        EWR  ORD
31        LGA  MIA
33        EWR  MSP
34        LGA  MSP
36        JFK  SJU
38        LGA  ORD
39        LGA  BWI
41        EWR  IAD
42        LGA  DFW
57        LGA  ORD
58        JFK  MCO
59        LGA  XNA
63        JFK  LAX
64        LGA  MIA
72        JFK  FLL
74        LGA  MKE
77        LGA  DFW
78        EWR  SEA
79        EWR  DFW
82        JFK  SFO
88        LGA  ORD
91        JFK  LAX
94        JFK  SFO
...       ...  ...
336726    EWR  MSY
336727    LGA  CLT
336730    EWR  RIC
336731    EWR  OKC
336733    LGA  ILM
336734    EWR  TUL
336735    EWR  JAX
336736    LGA  MDW
336739    EWR  MSP
336740    LGA  DTW
336741    EWR  SDF
336742    EWR  MCI
336745    EWR  DCA
336746    LGA  CHO
336747    EWR  CLT
336749    LGA  RIC
336750    JFK  DCA
336751    JFK  LAX
336752    EWR  PWM
336756    EWR  MHT
336757    JFK  BUF
336758    LGA  BGR
336759    LGA  BNA
336760    EWR  STL
336770    LGA  BNA
336771    JFK  DCA
336772    LGA  SYR
336773    LGA  BNA
336774    LGA  CLE
336775    LGA  RDU

[154830 rows x 2 columns]

In [135]:
df[~df['carrier'].isin(['US', 'UA', 'DL', 'B6'])][['origin', 'dest']] # dinegasikan

       origin dest
2         JFK  MIA
7         LGA  IAD
9         LGA  ORD
14        LGA  DFW
18        LGA  ATL
21        LGA  DTW
22        EWR  MIA
25        EWR  ORD
31        LGA  MIA
33        EWR  MSP
34        LGA  MSP
36        JFK  SJU
38        LGA  ORD
39        LGA  BWI
41        EWR  IAD
42        LGA  DFW
57        LGA  ORD
58        JFK  MCO
59        LGA  XNA
63        JFK  LAX
64        LGA  MIA
72        JFK  FLL
74        LGA  MKE
77        LGA  DFW
78        EWR  SEA
79        EWR  DFW
82        JFK  SFO
88        LGA  ORD
91        JFK  LAX
94        JFK  SFO
...       ...  ...
336726    EWR  MSY
336727    LGA  CLT
336730    EWR  RIC
336731    EWR  OKC
336733    LGA  ILM
336734    EWR  TUL
336735    EWR  JAX
336736    LGA  MDW
336739    EWR  MSP
336740    LGA  DTW
336741    EWR  SDF
336742    EWR  MCI
336745    EWR  DCA
336746    LGA  CHO
336747    EWR  CLT
336749    LGA  RIC
336750    JFK  DCA
336751    JFK  LAX
336752    EWR  PWM
336756    EWR  MHT
336757    JFK  BUF
336758    LGA  BGR
336759    LGA  BNA
336760    EWR  STL
336770    LGA  BNA
336771    JFK  DCA
336772    LGA  SYR
336773    LGA  BNA
336774    LGA  CLE
336775    LGA  RDU

[154830 rows x 2 columns]

Berapa penerbangan yang terlaksana di setiap bulannya?

In [127]:
df3 = df.sort_values(by = 'dep_time').dropna()

i = 1

for i in range(1,13,1):
    df3m = df3[df3['month' == i]].count()

print(df3m)

KeyError: False

In [136]:
df[df['dep_time'].notna()][['month', 'flight']].groupby(by = ['month']).count()
# menampilkan semua baris yang tiap elemen ada isinya, dapat dataframe yang berisi baris-baris yang memenuhi (tanpa nilai NaN)

       flight
month
1       26483
2       23690
3       27973
4       27662
5       28233
6       27234
7       28485
8       28841
9       27122
10      28653
11      27035
12      27110

Berapa banyak penerbangan setiap bulannya untuk setiap maskapai?

In [137]:
df[df['dep_time'].notna()][['month', 'carrier', 'flight']].groupby(by = ['month', 'carrier']).count()

               flight
month carrier
1     9E         1498
      AA         2735
      AS           62
      B6         4418
      DL         3661
      EV         3989
      F9           59
      FL          324
      HA           31
      MQ         2206
      OO            1
      UA         4605
      US         1555
      VX          315
      WN          985
      YV           39
2     9E         1353
      AA         2405
      AS           54
      B6         3950
      DL         3312
      EV         3558
      F9           48
      FL          282
      HA           28
      MQ         1904
      UA         4166
      US         1462
      VX          261
      WN          861
...               ...
11    AA         2558
      AS           52
      B6         4286
      DL         3847
      EV         4389
      F9           60
      FL          202
      HA           25
      MQ         2011
      OO            5
      UA         4838
      US         1668
      VX          443
      WN         1028
      YV           48
12    9E         1544
      AA         2599
      AS           54
      B6         4670
      DL         4076
      EV         3909
      F9           61
      FL          208
      HA           28
      MQ         1998
      UA         4833
      US         1544
      VX          468
      WN         1074
      YV           44

[185 rows x 1 columns]

Berikan jumlah penerbangan setiap maskapai untuk setiap bulan jika jumlah tersebut melebihi 2000.

In [140]:
grouped = df[df['dep_time'].notna()][['month', 'carrier', 'flight']].groupby(by = ['month', 'carrier']).count()
grouped = grouped.count() # hasil ekspresi ini adalah sebuah dataframe lagi
grouped[grouped['flight'] > 2000]

185